In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("hotel_bookings.csv")

In [3]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

In [5]:
df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [6]:
df = df.drop(columns=["company"])

In [7]:
df["agent"] = df["agent"].fillna(0)

In [8]:
df["arrival_date_month"] = pd.to_datetime(
    df["arrival_date_month"], format="%B"
).dt.month

In [9]:
df["arrival_date"] = pd.to_datetime(
    df[[
        "arrival_date_year",
        "arrival_date_month",
        "arrival_date_day_of_month"
    ]].rename(columns={
        "arrival_date_year": "year",
        "arrival_date_month": "month",
        "arrival_date_day_of_month": "day"
    })
)

In [10]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,2015,7,27,1,0,0,2,...,No Deposit,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01
1,Resort Hotel,0,737,2015,7,27,1,0,0,2,...,No Deposit,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01
2,Resort Hotel,0,7,2015,7,27,1,0,1,1,...,No Deposit,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
3,Resort Hotel,0,13,2015,7,27,1,0,1,1,...,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,2015,7,27,1,0,2,2,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,8,35,30,2,5,2,...,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017-08-30
119386,City Hotel,0,102,2017,8,35,31,2,5,3,...,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017-08-31
119387,City Hotel,0,34,2017,8,35,31,2,5,2,...,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017-08-31
119388,City Hotel,0,109,2017,8,35,31,2,5,2,...,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017-08-31
119389,City Hotel,0,205,2017,8,35,29,2,7,2,...,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017-08-29

In [11]:
df = df.drop(columns=[
    "arrival_date_year",
    "arrival_date_month",
    "arrival_date_day_of_month"
])

In [12]:
df

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,No Deposit,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,No Deposit,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,No Deposit,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017-08-30
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017-08-31
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017-08-31
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017-08-31
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017-08-29

In [13]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015-07-01
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,No Deposit,0.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015-07-01

In [14]:
df["arrival_date"].dtype

dtype('<M8[us]')

In [15]:
df["day_of_week"] = df["arrival_date"].dt.day_name()

In [16]:
df

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,day_of_week
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017-08-30,Wednesday
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017-08-31,Thursday
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017-08-31,Thursday
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017-08-31,Thursday
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017-08-29,Tuesday

In [17]:
df['is_canceled'].mean()

np.float64(0.37041628277075134)

In [18]:
df.groupby("hotel")["is_canceled"].mean()

hotel
City Hotel      0.417270
Resort Hotel    0.277634
Name: is_canceled, dtype: float64

In [19]:
df.groupby("day_of_week")["is_canceled"].mean()

day_of_week
Friday       0.406398
Monday       0.340928
Saturday     0.394849
Sunday       0.322749
Thursday     0.411707
Tuesday      0.328595
Wednesday    0.361299
Name: is_canceled, dtype: float64

In [20]:
df.groupby("lead_time")["is_canceled"].mean()

lead_time
0      0.067770
1      0.092775
2      0.102948
3      0.100220
4      0.102624
         ...
622    1.000000
626    1.000000
629    1.000000
709    0.000000
737    0.000000
Name: is_canceled, Length: 479, dtype: float64

In [21]:
df["lead_time_group"] = pd.cut(
    df["lead_time"],
    bins=[0, 30, 90, 180, 365, 700],
    labels=["0-30", "30-90", "90-180", "180-365", "365+"]
)

In [22]:
df.groupby("lead_time_group")["is_canceled"].mean()

lead_time_group
0-30       0.208739
30-90      0.376984
90-180     0.447105
180-365    0.554540
365+       0.677050
Name: is_canceled, dtype: float64

In [23]:
df.duplicated().sum()

np.int64(32001)

In [24]:
df.duplicated(subset=[
    "hotel",
    "arrival_date",
    "adr",
    "adults"
]).sum()

np.int64(58116)

In [25]:
df[df.duplicated()].head()

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,day_of_week,lead_time_group
5,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01,Wednesday,0-30
22,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,...,0,Transient,84.67,0,1,Check-Out,2015-07-07,2015-07-01,Wednesday,30-90
43,Resort Hotel,0,70,27,2,3,2,0.0,0,HB,...,0,Transient,137.00,0,1,Check-Out,2015-07-07,2015-07-02,Thursday,30-90
138,Resort Hotel,1,5,28,1,0,2,0.0,0,BB,...,0,Transient,97.00,0,0,Canceled,2015-07-01,2015-07-05,Sunday,0-30
200,Resort Hotel,0,0,28,0,1,1,0.0,0,BB,...,0,Transient,109.80,0,3,Check-Out,2015-07-08,2015-07-07,Tuesday,NaN

In [26]:
df.groupby("is_canceled")["adr"].mean()

is_canceled
0     99.987693
1    104.964333
Name: adr, dtype: float64

In [27]:
df.groupby("deposit_type")["is_canceled"].mean()

deposit_type
No Deposit    0.283770
Non Refund    0.993624
Refundable    0.222222
Name: is_canceled, dtype: float64

In [28]:
df["deposit_type"].value_counts()

deposit_type
No Deposit    104641
Non Refund     14587
Refundable       162
Name: count, dtype: int64

In [29]:
df['hotel']=df['hotel'].str.strip()

In [30]:
df

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,day_of_week,lead_time_group
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday,180-365
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday,NaN
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday,0-30
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday,0-30
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01,Wednesday,0-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017-08-30,Wednesday,0-30
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017-08-31,Thursday,90-180
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017-08-31,Thursday,30-90
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017-08-31,Thursday,90-180
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017-08-29,Tuesday,180-365

In [31]:
df.columns = df.columns.str.replace("_", " ").str.title()

In [32]:
df

,Hotel,Is Canceled,Lead Time,Arrival Date Week Number,Stays In Weekend Nights,Stays In Week Nights,Adults,Children,Babies,Meal,...,Days In Waiting List,Customer Type,Adr,Required Car Parking Spaces,Total Of Special Requests,Reservation Status,Reservation Status Date,Arrival Date,Day Of Week,Lead Time Group
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday,180-365
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday,NaN
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday,0-30
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday,0-30
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01,Wednesday,0-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017-08-30,Wednesday,0-30
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017-08-31,Thursday,90-180
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017-08-31,Thursday,30-90
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017-08-31,Thursday,90-180
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017-08-29,Tuesday,180-365

In [33]:
df["month"] = df["Arrival Date"].dt.month_name()

In [34]:
df

,Hotel,Is Canceled,Lead Time,Arrival Date Week Number,Stays In Weekend Nights,Stays In Week Nights,Adults,Children,Babies,Meal,...,Customer Type,Adr,Required Car Parking Spaces,Total Of Special Requests,Reservation Status,Reservation Status Date,Arrival Date,Day Of Week,Lead Time Group,month
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday,180-365,July
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday,NaN,July
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday,0-30,July
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday,0-30,July
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01,Wednesday,0-30,July
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,Transient,96.14,0,0,Check-Out,2017-09-06,2017-08-30,Wednesday,0-30,August
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,Transient,225.43,0,2,Check-Out,2017-09-07,2017-08-31,Thursday,90-180,August
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,Transient,157.71,0,4,Check-Out,2017-09-07,2017-08-31,Thursday,30-90,August
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,Transient,104.40,0,0,Check-Out,2017-09-07,2017-08-31,Thursday,90-180,August
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,Transient,151.20,0,2,Check-Out,2017-09-07,2017-08-29,Tuesday,180-365,August

In [35]:
df["Is Weekend"] = df["Day Of Week"].isin(["Saturday", "Sunday"])

In [36]:
df

,Hotel,Is Canceled,Lead Time,Arrival Date Week Number,Stays In Weekend Nights,Stays In Week Nights,Adults,Children,Babies,Meal,...,Adr,Required Car Parking Spaces,Total Of Special Requests,Reservation Status,Reservation Status Date,Arrival Date,Day Of Week,Lead Time Group,month,Is Weekend
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday,180-365,July,False
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,2015-07-01,Wednesday,NaN,July,False
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday,0-30,July,False
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-02,2015-07-01,Wednesday,0-30,July,False
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,98.00,0,1,Check-Out,2015-07-03,2015-07-01,Wednesday,0-30,July,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,96.14,0,0,Check-Out,2017-09-06,2017-08-30,Wednesday,0-30,August,False
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,225.43,0,2,Check-Out,2017-09-07,2017-08-31,Thursday,90-180,August,False
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,157.71,0,4,Check-Out,2017-09-07,2017-08-31,Thursday,30-90,August,False
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,104.40,0,0,Check-Out,2017-09-07,2017-08-31,Thursday,90-180,August,False
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,151.20,0,2,Check-Out,2017-09-07,2017-08-29,Tuesday,180-365,August,False

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Hotel                           119390 non-null  str
 1   Is Canceled                     119390 non-null  int64
 2   Lead Time                       119390 non-null  int64
 3   Arrival Date Week Number        119390 non-null  int64
 4   Stays In Weekend Nights         119390 non-null  int64
 5   Stays In Week Nights            119390 non-null  int64
 6   Adults                          119390 non-null  int64
 7   Children                        119386 non-null  float64
 8   Babies                          119390 non-null  int64
 9   Meal                            119390 non-null  str
 10  Country                         118902 non-null  str
 11  Market Segment                  119390 non-null  str
 12  Distribution Channel            119390 non-null  str
 13  Is Repeated Guest               119390 non-null  int64
 14  Previous Cancellations          119390 non-null  int64
 15  Previous Bookings Not Canceled  119390 non-null  int64
 16  Reserved Room Type              119390 non-null  str
 17  Assigned Room Type              119390 non-null  str
 18  Booking Changes                 119390 non-null  int64
 19  Deposit Type                    119390 non-null  str
 20  Agent                           119390 non-null  float64
 21  Days In Waiting List            119390 non-null  int64
 22  Customer Type                   119390 non-null  str
 23  Adr                             119390 non-null  float64
 24  Required Car Parking Spaces     119390 non-null  int64
 25  Total Of Special Requests       119390 non-null  int64
 26  Reservation Status              119390 non-null  str
 27  Reservation Status Date         119390 non-null  str
 28  Arrival Date                    119390 non-null  datetime64[us]
 29  Day Of Week                     119390 non-null  str
 30  Lead Time Group                 113043 non-null  category
 31  month                           119390 non-null  str
 32  Is Weekend                      119390 non-null  bool
dtypes: bool(1), category(1), datetime64[us](1), float64(3), int64(14), str(13)
memory usage: 28.5 MB

In [38]:
df = df.drop(columns=[
    "Reservation Status Date"
])

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Hotel                           119390 non-null  str
 1   Is Canceled                     119390 non-null  int64
 2   Lead Time                       119390 non-null  int64
 3   Arrival Date Week Number        119390 non-null  int64
 4   Stays In Weekend Nights         119390 non-null  int64
 5   Stays In Week Nights            119390 non-null  int64
 6   Adults                          119390 non-null  int64
 7   Children                        119386 non-null  float64
 8   Babies                          119390 non-null  int64
 9   Meal                            119390 non-null  str
 10  Country                         118902 non-null  str
 11  Market Segment                  119390 non-null  str
 12  Distribution Channel            119390 non-null  str
 13  Is Repeated Guest               119390 non-null  int64
 14  Previous Cancellations          119390 non-null  int64
 15  Previous Bookings Not Canceled  119390 non-null  int64
 16  Reserved Room Type              119390 non-null  str
 17  Assigned Room Type              119390 non-null  str
 18  Booking Changes                 119390 non-null  int64
 19  Deposit Type                    119390 non-null  str
 20  Agent                           119390 non-null  float64
 21  Days In Waiting List            119390 non-null  int64
 22  Customer Type                   119390 non-null  str
 23  Adr                             119390 non-null  float64
 24  Required Car Parking Spaces     119390 non-null  int64
 25  Total Of Special Requests       119390 non-null  int64
 26  Reservation Status              119390 non-null  str
 27  Arrival Date                    119390 non-null  datetime64[us]
 28  Day Of Week                     119390 non-null  str
 29  Lead Time Group                 113043 non-null  category
 30  month                           119390 non-null  str
 31  Is Weekend                      119390 non-null  bool
dtypes: bool(1), category(1), datetime64[us](1), float64(3), int64(14), str(12)
memory usage: 27.6 MB

In [40]:
df['month']=df['month'].str.title()

In [41]:
df["Cancellation Label"] = df["Is Canceled"].map({
    0: "Not Canceled",
    1: "Canceled"
})

In [42]:
df

,Hotel,Is Canceled,Lead Time,Arrival Date Week Number,Stays In Weekend Nights,Stays In Week Nights,Adults,Children,Babies,Meal,...,Adr,Required Car Parking Spaces,Total Of Special Requests,Reservation Status,Arrival Date,Day Of Week,Lead Time Group,month,Is Weekend,Cancellation Label
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Wednesday,180-365,July,False,Not Canceled
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Wednesday,NaN,July,False,Not Canceled
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,98.00,0,1,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,96.14,0,0,Check-Out,2017-08-30,Wednesday,0-30,August,False,Not Canceled
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,225.43,0,2,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,157.71,0,4,Check-Out,2017-08-31,Thursday,30-90,August,False,Not Canceled
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,104.40,0,0,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,151.20,0,2,Check-Out,2017-08-29,Tuesday,180-365,August,False,Not Canceled

In [43]:
df["Lead Time Group"] = pd.cut(
    df["Lead Time"],
    bins=[-1, 30, 90, 180, 365, 1000],
    labels=["0-30", "30-90", "90-180", "180-365", "365+"]
)

In [44]:
df

,Hotel,Is Canceled,Lead Time,Arrival Date Week Number,Stays In Weekend Nights,Stays In Week Nights,Adults,Children,Babies,Meal,...,Adr,Required Car Parking Spaces,Total Of Special Requests,Reservation Status,Arrival Date,Day Of Week,Lead Time Group,month,Is Weekend,Cancellation Label
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Wednesday,180-365,July,False,Not Canceled
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Wednesday,365+,July,False,Not Canceled
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,98.00,0,1,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,96.14,0,0,Check-Out,2017-08-30,Wednesday,0-30,August,False,Not Canceled
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,225.43,0,2,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,157.71,0,4,Check-Out,2017-08-31,Thursday,30-90,August,False,Not Canceled
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,104.40,0,0,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,151.20,0,2,Check-Out,2017-08-29,Tuesday,180-365,August,False,Not Canceled

In [45]:
df['Lead Time Group'].value_counts()

Lead Time Group
0-30       38706
30-90      29553
90-180     26439
180-365    21544
365+        3148
Name: count, dtype: int64

In [46]:
df['Days In Waiting List'].info()

<class 'pandas.Series'>
RangeIndex: 119390 entries, 0 to 119389
Series name: Days In Waiting List
Non-Null Count   Dtype
--------------   -----
119390 non-null  int64
dtypes: int64(1)
memory usage: 932.9 KB

In [47]:
df['Country'].isna().sum()

np.int64(488)

In [48]:
df['Country'].info()

<class 'pandas.Series'>
RangeIndex: 119390 entries, 0 to 119389
Series name: Country
Non-Null Count   Dtype
--------------   -----
118902 non-null  str
dtypes: str(1)
memory usage: 932.9 KB

In [49]:
df.columns = df.columns.str.replace(" ", "_")

In [50]:
df

,Hotel,Is_Canceled,Lead_Time,Arrival_Date_Week_Number,Stays_In_Weekend_Nights,Stays_In_Week_Nights,Adults,Children,Babies,Meal,...,Adr,Required_Car_Parking_Spaces,Total_Of_Special_Requests,Reservation_Status,Arrival_Date,Day_Of_Week,Lead_Time_Group,month,Is_Weekend,Cancellation_Label
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Wednesday,180-365,July,False,Not Canceled
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Wednesday,365+,July,False,Not Canceled
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,98.00,0,1,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,96.14,0,0,Check-Out,2017-08-30,Wednesday,0-30,August,False,Not Canceled
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,225.43,0,2,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,157.71,0,4,Check-Out,2017-08-31,Thursday,30-90,August,False,Not Canceled
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,104.40,0,0,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,151.20,0,2,Check-Out,2017-08-29,Tuesday,180-365,August,False,Not Canceled

In [51]:
df.columns = df.columns.str.lower()

In [52]:
df

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,arrival_date,day_of_week,lead_time_group,month,is_weekend,cancellation_label
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Wednesday,180-365,July,False,Not Canceled
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Wednesday,365+,July,False,Not Canceled
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,98.00,0,1,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,96.14,0,0,Check-Out,2017-08-30,Wednesday,0-30,August,False,Not Canceled
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,225.43,0,2,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,157.71,0,4,Check-Out,2017-08-31,Thursday,30-90,August,False,Not Canceled
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,104.40,0,0,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,151.20,0,2,Check-Out,2017-08-29,Tuesday,180-365,August,False,Not Canceled

In [53]:
df["month_num"] = df["arrival_date"].dt.month

In [54]:
df.to_csv("hotel_cleaned_final.csv", index=False)

In [55]:
df["month_num"]

0         7
1         7
2         7
3         7
4         7
         ..
119385    8
119386    8
119387    8
119388    8
119389    8
Name: month_num, Length: 119390, dtype: int32

In [56]:
df

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,required_car_parking_spaces,total_of_special_requests,reservation_status,arrival_date,day_of_week,lead_time_group,month,is_weekend,cancellation_label,month_num
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0,0,Check-Out,2015-07-01,Wednesday,180-365,July,False,Not Canceled,7
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0,0,Check-Out,2015-07-01,Wednesday,365+,July,False,Not Canceled,7
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled,7
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,0,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled,7
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,0,1,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,0,0,Check-Out,2017-08-30,Wednesday,0-30,August,False,Not Canceled,8
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,0,2,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled,8
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,0,4,Check-Out,2017-08-31,Thursday,30-90,August,False,Not Canceled,8
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,0,0,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled,8
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,0,2,Check-Out,2017-08-29,Tuesday,180-365,August,False,Not Canceled,8

In [57]:
df.to_csv("hotel_cleaned_final.csv", index=False)

In [58]:
df["day_num"] = df["arrival_date"].dt.dayofweek

In [59]:
df

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,total_of_special_requests,reservation_status,arrival_date,day_of_week,lead_time_group,month,is_weekend,cancellation_label,month_num,day_num
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0,Check-Out,2015-07-01,Wednesday,180-365,July,False,Not Canceled,7,2
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0,Check-Out,2015-07-01,Wednesday,365+,July,False,Not Canceled,7,2
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled,7,2
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,0,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled,7,2
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,1,Check-Out,2015-07-01,Wednesday,0-30,July,False,Not Canceled,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,0,Check-Out,2017-08-30,Wednesday,0-30,August,False,Not Canceled,8,2
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,2,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled,8,3
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,4,Check-Out,2017-08-31,Thursday,30-90,August,False,Not Canceled,8,3
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,0,Check-Out,2017-08-31,Thursday,90-180,August,False,Not Canceled,8,3
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,2,Check-Out,2017-08-29,Tuesday,180-365,August,False,Not Canceled,8,1

In [60]:
df.to_csv("hotel_cleaned_final.csv", index=False)